### ISSUE TITLE
File name of the artifacts

### ISSUE THREAD

**Issue by nrryuya** [maurelian/truper#1]
Thank you for your great work!

Is there any reason why truper compiler outputs `myContract.vyper.json`  instead of `myContract.json` ?

Truffle migration makes `myContract.json` so the first `myContract.vyper.json` is not overwritten. Therefore, when I did `const MyContract = artifacts.require('myContract.vyper');`  we can not access the contract with the `MyContract` variable in truffle console. (It raises `MyContract has no network configuration for its current network id` error.)

**Comment by nemani** [comment]
@maurelian This is an actual issue. I will create a PR for the same. 
I have tested that after making this change, we can interact with the contract in truffle console with `contract.deployed()` :grin:

**Comment by nemani** [comment]
Anyway I think this repo will be obselete once https://github.com/trufflesuite/truffle/pull/1240 is merged.

**Comment by maurelian** [comment]
Thanks @nemaniarjun, and sorry for not maintaining more actively. 

I've always considered this tool more of a stop gap measure, assuming Truffle would eventually subsume it.

**Comment by maurelian** [comment]
Oh, and I merged the PR.
